### ISSUE TITLE
Hide and Seek In A Box?

### ISSUE THREAD

**Issue by aadharna** [TomGeorge1234/RatInABox#66]
I just stumbled upon this from your gymnasium compliance tweet. 

I was wondering how feasible would it be to combine the field of view + multi-agent + new gym wrapper classes to create a hide-and-seek environment similar to [mujoco-based works](https://arxiv.org/abs/1909.07528) (with bonus points if you could also move walls around) using the tools here? 

If not, and if this isn't something you'd have interest in having in here, no worries.

**Comment by TomGeorge1234** [comment]
This would be awesome. I'd definitely put it on the "harder" side of the spectrum but totally within scope, particularly if you know what you're doing. 

Some of this isn't natively supported but wouldn't be hard to do, for example Agents moving walls around isn't supported but you could totally reach in, access the walls parameter, then manually adjust one by a small amount depending, say, on the Agents position/velocity.

If you got it working I'd be thrilled to have it here as a contrib/demo. I'm sure people would use it. Happy to chat further if you're seriously considering this.

**Comment by aadharna** [comment]
Definitely interested and serious about it! 

With how my schedule looks at the moment I probably won't get to this for a couple of weeks, but once my agents can crush my current environment, H&S is the logical next domain.

**Comment by TomGeorge1234** [comment]
Are you current Agents in RiaB or something else? 

Yeah, take your time, but I'd be excited to support this. Get back in touch when you're ready/if you need support.

**Comment by aadharna** [comment]
My agents are just pytorch NNs -- no notion of firing rates, etc -- I do pure deep rl (and for this project am training agents via historical self-play).

My environments are a mix of homemade games (a weird one-step cooperative multi-agent game, and an iterated competitive matrix game) and board games (Connect 4, Go, etc) right now. 

A stretch goal for the research is to get something similar to the Open AI H&S domain I linked above, but that's not the focus at the moment while I iterate on the main scientific contributions in simple environments.

**Comment by TomGeorge1234** [comment]
Hi Aaron, I just remembered this discussion - did you ever move forwards with it, was wondering how you got on?

**Comment by aadharna** [comment]
Hey Tom!

I am still interested; however, my advisor told me to put that on hold until after I finish up with quals. So, no movement yet.
