### ISSUE TITLE
Please tag the 1.9.1 release

### ISSUE THREAD

**Issue by musicinmybrain** [TomGeorge1234/RatInABox#78]
Could you please push the git tag for the 1.9.1 release now on PyPI?

I think it should be `v1.9.1` referencing 23f21b3c23e4a92464625704b04ae5f00a0e16c2.

Thanks!

**Comment by TomGeorge1234** [comment]
Hi sorry for the slow reply, I've been away. Thanks for the reminder, I just tagged it: https://github.com/TomGeorge1234/RatInABox/releases/tag/v1.9.1

**Comment by musicinmybrain** [comment]
Thanks!
