### ISSUE TITLE
Minimum required python version currently 3.10

### ISSUE THREAD

**Issue by stes** [TomGeorge1234/RatInABox#79]
Thanks for your work on this package!

I noticed that the setup file mentions python 3.7 as the minimum version,

https://github.com/TomGeorge1234/RatInABox/blob/23f21b3c23e4a92464625704b04ae5f00a0e16c2/setup.cfg#L28

However, certain features in the code like the "|" notation for type annotations were only introduced in python 3.10

https://github.com/TomGeorge1234/RatInABox/blob/23f21b3c23e4a92464625704b04ae5f00a0e16c2/ratinabox/utils.py#L1079

Cf https://docs.python.org/3.10/library/typing.html

![image](https://github.com/TomGeorge1234/RatInABox/assets/727984/6fef7e8d-2744-4b3e-9ef1-c299b2ad86e5)

I think it would be good to either:

-- clarify the python version in the setup.cfg, and bump it to `>= 3.10`
-- replace the problematic statements (I would guess it is only very few of them) to make the code compatible with e.g. at least python 3.8

Thoughts?

**Comment by TomGeorge1234** [comment]
Hi Stefan! Thanks for flagging this and slow for my slow reply as I've been away. 

I think for now I'm happy to bump python requirements to `>=3.10` so we can continue development using these new features. Better type hinting is something we hope to improve in upcoming versions. I've bumped the requirement and published this under v1.9.2. 

I'll leave this issue open for a few days so if anybody seems to have problems they can outline them here and we can consider reversing if needed.

**Comment by TomGeorge1234** [comment]
Fyi @stes in the end after discussing with @CYHSM we did renege on this so RiaB remain compatible with python >=3.7. See PR #81 

https://github.com/TomGeorge1234/RatInABox/blob/b545df61216d6aa14169a856ce32ddad5d0516f6/setup.cfg#L28
